file:
  upload-dir: src/main/resources/static/rescue_informaition   # 保存目录（相对或绝对均可）
  access-prefix: /rescue_informaition/                        # 返回给前端的统一前缀
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML
#这是数据库的依赖
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.76.205:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 114514
    username: root
    hikari:
      max-lifetime: 300000
      idle-timeout: 60000
      connection-timeout: 30000
  redis: # redis配置
    database: 0
    host: 123.249.76.205
    password: 700101
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  mail:
    host: smtp.qq.com
    port: 465
    username: 1807367347@qq.com
    password: xrcozyawmyzqegci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB


# 阿里云短信配置
aliyun:
  sms:
    access-key-id: LTAI5tPRQ2mjozsgWb5qpgLZ
    access-key-secret: bJklOOdXvXc2tctX92njTWI8ldTIkJ
    sign-name: 智寻归途
    template-code: SMS_474630233

xfyun:
  requestUrl: https://api.xf-yun.com/v1/private/s782b4996
  appId: 609426a3
  apiKey: d8b1264bbeb1ed0095111f2e595f9ea9
  apiSecret: NTUwMzRjMDQxMDAwNTY3NTYzYTg2YWZl


mybatis:
  type-handlers-package: com.maka.typehandler
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.maka.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.maka.mapper: debug
    org.mybatis: debug
    org.springframework.jdbc.datasource: debug
    # 添加 Thymeleaf 相关日志
    org.thymeleaf: debug
    org.thymeleaf.TemplateEngine: debug
    org.thymeleaf.spring5: debug
    org.springframework.web: debug
server:
  port: 8080
