file:
  upload-dir: uploads           # 这里就是项目根目录下的uploads
  access-prefix: /uploads/
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML
#这是数据库的依赖
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.76.205:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 114514
    username: root
    hikari:
      maximum-pool-size: 20
      max-lifetime: 240000      # Reduced to 4 minutes
      idle-timeout: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis: # redis配置
    database: 0
    host: 123.249.76.205
    password: 700101
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  mail:
    host: smtp.qq.com
    port: 465
    username: 1807367347@qq.com
    password: xrcozyawmyzqegci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB


# 阿里云短信配置
aliyun:
  sms:
    access-key-id: LTAI5tPnjpyq2RfKmWyXFDsy
    access-key-secret: 04ynGElOHbltHcVlugc0eNWl3MC9eK
    sign-name: 智寻归途
    template-code: SMS_474630233

xfyun:
  requestUrl: https://api.xf-yun.com/v1/private/s782b4996
  appId: b2648935
  apiKey: 1af07890f43226ae5eee242776b69feb
  apiSecret: OWFhNGZhOTU1YTQzNmIxOTFjZWI0Njc4


mybatis:
  type-handlers-package: com.maka.typehandler
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.maka.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.maka.mapper: debug
    org.mybatis: debug
    org.springframework.jdbc.datasource: debug
    # 添加 Thymeleaf 相关日志
    org.thymeleaf: debug
    org.thymeleaf.TemplateEngine: debug
    org.thymeleaf.spring5: debug
    org.springframework.web: debug
server:
  port: 8080

# 高德地图API密钥
amap.key: 2a73ff764995703ff9e17cc103851a1e